### ISSUE TITLE
Blender file not available with LFS

### ISSUE THREAD

**Issue by dneuhof** [NeLy-EPFL/NeuroMechFly#47] opened 2023-03-27 11:44 UTC
Hello @gizemozd ,
I cannot fetch the blender file with `git clone lfs`:
```
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/NeLy-EPFL/NeuroMechFly.git/info/lfs'
```

_Originally posted by @dneuhof in https://github.com/NeLy-EPFL/NeuroMechFly/issues/45#issuecomment-1484994468_

**Comment by gizemozd** [comment] 2023-03-27 13:05
Hi @dneuhof,

Thanks for reporting this issue!
You are right; the issue was caused by a repo exceeding the data storage quota. I have cleaned up the storage; however, updating the quota information will take Github a while. Until then, [here](https://filesender.switch.ch/filesender2/?s=download&token=95648d69-3e3c-45a9-ba83-243d8c827dc1) is a link to download the Blender file.

**Comment by gizemozd** [comment] 2023-03-27 18:15
Closing this issue because the quota seems to be updated now.

**Closed by gizemozd** 2023-03-27 18:15 UTC
